// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAljIr4zwJ8-ap9fwPS7arXTcoDgoy1A-8',
    appId: '1:401963892153:web:8a071c430723d2ad978a68',
    messagingSenderId: '401963892153',
    projectId: 'appointments-5b541',
    authDomain: 'appointments-5b541.firebaseapp.com',
    storageBucket: 'appointments-5b541.appspot.com',
    measurementId: 'G-1ZKDTLWNEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcAr849yPM2wxG4kwEE2f-MiMm53w--4',
    appId: '1:401963892153:android:118d73779cf67e78978a68',
    messagingSenderId: '401963892153',
    projectId: 'appointments-5b541',
    storageBucket: 'appointments-5b541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1UOHpLygsdAyLF9H8kbZrCrox7QMA8jo',
    appId: '1:401963892153:ios:e18fb00b83598edc978a68',
    messagingSenderId: '401963892153',
    projectId: 'appointments-5b541',
    storageBucket: 'appointments-5b541.appspot.com',
    androidClientId: '401963892153-8inv89kmob5fp3h89vie9rkdbb9gen87.apps.googleusercontent.com',
    iosClientId: '401963892153-gpq59i5t6a760smnqoh47pje27a73uup.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1UOHpLygsdAyLF9H8kbZrCrox7QMA8jo',
    appId: '1:401963892153:ios:4fe67444cc36f4b6978a68',
    messagingSenderId: '401963892153',
    projectId: 'appointments-5b541',
    storageBucket: 'appointments-5b541.appspot.com',
    androidClientId: '401963892153-8inv89kmob5fp3h89vie9rkdbb9gen87.apps.googleusercontent.com',
    iosClientId: '401963892153-l4ree5ij24uv6p8mc87f7ojum7o3di77.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointments.RunnerTests',
  );
}
